apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: spring-sensors
  name: spring-sensors
spec:
  ports:
  - name: 80-8080
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: spring-sensors
  type: LoadBalancer
status:
  loadBalancer: {}
