server:
  port: 9090
spring:
  config:
    import: "optional:configserver:"
  application:
    name: spring-sensors-location-service
---
spring:
  config:
    activate:
      on-cloud-platform: kubernetes
    import: configserver:http://spring-cloud-kubernetes-configserver:8888