spring:
  cloud:
    stream.bindings.sendSensorData-out-0.destination: sensor-data
    discovery:
      client:
        health-indicator:
          enabled: false
org:
  springframework:
    cloud:
      bindings:
        boot:
          enable: true