apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: spring-sensors-location-service
  name: spring-sensors-location-service
spec:
  ports:
  - name: 80-9090
    port: 80
    protocol: TCP
    targetPort: 9090
  selector:
    app: spring-sensors-location-service
  type: ClusterIP
status:
  loadBalancer: {}
