spring:
  config:
    import: "optional:configserver:"
  application:
    name: spring-sensors
title: Sensor Database
---
spring:
  config:
    activate:
      on-cloud-platform: kubernetes
    import: configserver:http://spring-cloud-kubernetes-configserver:8888